### PR TITLE
Project structure and docker creation script

### PR DESCRIPTION
**Pull request by pvdochtend**
My first wish was to be able to run this script as a docker image.
Therefore I needed to move the config file to a separate folder (so I can connect it to a persistent volume outside the docker image.
Also I moved the python files that are not needed for execution (all except 3cqsbot.py) o a helper folder.

I added some simple instruction to create the docker image.

### CODE REVIEW

**Comment by pvdochtend** [comment]
Synced with the latest commit. I hope other people will find it very useful to be able to run this script very easy from a docker image.

**Comment by TBMoonwalker** [comment]
@pvdochtend Thanks for the distribution, but I'm already working on it. It is not only docker, Kubernetes has to be observed too. I make the configuration file location configurable through command line (and logging too). Start should be done by a start script, to update the config.ini values through environment variables. Your code definitely works, but If I'm implementing this it should work for Cloud services too.

**Comment by pvdochtend** [comment]
Aaah.. Ok...

Those advantages are really nice.. Indeed the environment settings for the configuration would be nice.
Kubernetes just for the cloud perhaps. I don't know why someone would run that (paid) by the way, but that's offtopic :D

When are you releasing that version?

**Comment by TBMoonwalker** [comment]
@pvdochtend Release with Docker is out now. I close this PR.

**Pull request closed without merging**
